// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGistFile(arg1) {
  return window['go']['main']['App']['GetGistFile'](arg1);
}

export function GetGists() {
  return window['go']['main']['App']['GetGists']();
}

export function GetUser() {
  return window['go']['main']['App']['GetUser']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LogIn(arg1) {
  return window['go']['main']['App']['LogIn'](arg1);
}

export function LoggedIn() {
  return window['go']['main']['App']['LoggedIn']();
}
