// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {github} from '../models';

export function GetGists():Promise<Array<github.Gist>>;

export function Greet(arg1:string):Promise<string>;
