// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetGistFile(arg1:string):Promise<main.ReturnValue>;

export function GetGists():Promise<main.ReturnValue>;

export function GetUser():Promise<main.ReturnValue>;

export function Greet(arg1:main.Person):Promise<string>;

export function LogIn(arg1:string):Promise<main.ReturnValue>;

export function LoggedIn():Promise<boolean>;
